# This is a Jekyll configuration file
# ref: https://jekyllrb.com/docs/configuration/options/
#
# We make use of this theme, and it is what makes title and description have
# meaning.
# ref: https://github.com/pages-themes/minimal
theme: jekyll-theme-hacker

title: HKube's Helm chart repository
description: |
  This the human friendly view of the HKube's Helm chart repository
  where Helm charts developed elsewhere are published. The command line tool
  <code>helm</code> will interacts with <a href="index.yaml">index.yaml</a>.

# We also use custom variables accessed in index.md by {% site.variableName %}
stableCharts:
  - hkube

stableVersions:
  - v2.8
  - v2.7
  - v2.6
  - v2.5
  - v2.4
  - v2.3
  - v2.2
  - v2.1
  - v2.0
  - v1.3
  - v1.2
