
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: clean-old-jobs
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: clean-old-jobs
  labels:
    group: {{ .Values.lables.group.value }}
    app: clean-old-jobs
    core: "true"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clean-old-jobs
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.lables.group.value }}
    app: clean-old-jobs
    core: "true"
subjects:
- kind: ServiceAccount
  name: clean-old-jobs
roleRef:
  kind: Role
  name: clean-old-jobs
  apiGroup: rbac.authorization.k8s.io
